version: '3.8'

services:
  spring-vkapi:
    build: .
    environment:
      - VK_TOKEN=${VK_TOKEN}
      - VK_GROUP_ID=${VK_GROUP_ID}
      - LOGSTASH_HOST=${LOGSTASH_HOST}
      - LOGSTASH_PORT=${LOGSTASH_PORT}
      - VK_SECRET=${VK_SECRET}
      - VK_API_VERSION=${VK_API_VERSION}
    ports:
      - "8080:8080"
    depends_on:
      - logstash

  logstash:
    image: docker.elastic.co/logstash/logstash:7.17.4
    ports:
      - "5044:5044"
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
